In [53]:
pip install selenium==3.14.0

Collecting selenium==3.14.0
  Downloading selenium-3.14.0-py2.py3-none-any.whl (898 kB)
Requirement already satisfied: urllib3 in c:\users\arunk\anaconda3\lib\site-packages (from selenium==3.14.0) (1.26.4)
Installing collected packages: selenium
  Attempting uninstall: selenium
    Found existing installation: selenium 4.0.0
    Uninstalling selenium-4.0.0:
      Successfully uninstalled selenium-4.0.0
Successfully installed selenium-3.14.0
Note: you may need to restart the kernel to use updated packages.

In [840]:
import os
import re
import time
import csv
import json
import random
import requests
import pandas as pd
import numpy as np



from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys # give us access to enter and esc keys to send enter or escc keys to page
from selenium.webdriver.common.by import By
import time as tim
from selenium.webdriver.support.ui import WebDriverWait 
#An explicit wait is a code you define to wait for a certain condition to occur before proceeding further in the cod
from selenium.webdriver.support import expected_conditions as EC

In [2]:
options = webdriver.ChromeOptions()
options.headless = False
browser = webdriver.Chrome(executable_path = '/Users/arunk/Downloads/chromedriver',chrome_options = options)

In [115]:
chrome_options = webdriver.ChromeOptions()
chrome_options.headless = True
browser = webdriver.Chrome(
executable_path = '/Users/arunk/Downloads/chromedriver',
    chrome_options = chrome_options)

In [295]:
tickers_df = pd.read_csv('C:/Users/arunk/Downloads/msa8040_final_project_ticker_list.csv')
tickers_df.head()

  ticker
0    GPC
1    ALV
2   GNTX
3    VNE
4   TOWR

In [301]:
qtr_yr = ['fq3-2021','fq2-2021','fq1-2021','fq4-2020']

In [302]:
tick = str.lower('EHTH')
qtr_yr = 'fq3-2021'
link = 'https://www.estimize.com/'+tick+'/'+qtr_yr+'?metric_name=eps&chart=historical'

In [1077]:
import random
random.seed(46)
ticks=random.sample(list(tickers_df.ticker), 50)

In [1081]:
ticks

TypeError: list indices must be integers or slices, not tuple

### Company Information

In [1079]:
len(ticks)

50

In [1080]:
tick = ticks
#['EHTH','CTRN','ANDE','NHTC','PFGC','CVS','GO','SPTN','WMT','BJ','NGVC','KR','CASY','UNFI','IMKTA','COST','RAD']#18
tickers=[]
names=[]
sectors=[]
industries=[]
number_of_followers=[]
number_of_analysts=[]

options = webdriver.ChromeOptions()
options.headless = False
browser = webdriver.Chrome(executable_path = '/Users/arunk/Downloads/chromedriver',chrome_options = options)
link = 'https://www.estimize.com/edge'#+str.lower(tick[i])+'/fq3-2021?metric_name=eps&chart=historical'
browser.get(link)

for i in tick:

    search = browser.find_element_by_name('search') #return an object with value name 'search'
    search.send_keys(i) #feed search bar with text in the search bar
    search.send_keys(Keys.RETURN)
    
    time.sleep(3)
    
    ticker = browser.find_element_by_xpath("//*[@id='releases_show']/div[2]/div[2]/div/div[1]/div/div/div/div[1]/h1/a").text
    tickers.append(ticker)
    name = browser.find_element_by_xpath("//*[@id='releases_show']/div[2]/div[2]/div/div[1]/div/div/div/div[1]/p/a").text
    names.append(name)
    sector =  browser.find_element_by_xpath("//*[@id='releases_show']/div[2]/div[2]/div/div[1]/div/div/div/p/span[1]/a/span").text
    sectors.append(sector)
    ind = browser.find_element_by_xpath('//*[@id="releases_show"]/div[2]/div[2]/div/div[1]/div/div/div/p/span[2]/a/span').text
    industries.append(ind)
    numb_of_followers = browser.find_element_by_xpath("//*[@id='summary-stats']/div/div/div[1]/div[2]").text
    number_of_followers.append(numb_of_followers)
    numb_of_analysts = browser.find_element_by_xpath("//*[@id='summary-stats']/div/div/div[2]/a").text
    number_of_analysts.append(numb_of_analysts)

In [1082]:
company = pd.DataFrame(list(zip(tickers,names,sectors,industries,number_of_followers,number_of_analysts)),
               columns =['tickers','names','sectors','industries','number_of_followers','number_of_analysts'])

In [1083]:
company

,tickers,names,sectors,industries,number_of_followers,number_of_analysts
0,CVNA,Carvana Co.,Consumer Discretionary,Specialty Retail,71,42
1,FLEX,Flextronics International Ltd.,Information Technology,"Electronic Equip., Instruments",84,132
2,LZB,La-Z-Boy Inc.,Consumer Discretionary,Household Durables,77,212
3,ARNA,"Arena Pharmaceuticals, Inc.",Health Care,Biotechnology,67,81
4,ATI,Allegheny Technologies Inc.,Materials,Metals & Mining,64,124
5,DKL,"Delek Logistics Partners, LP",Energy,"Oil, Gas & Consumable Fuels",12,33
6,UGI,UGI Corp.,Utilities,Gas Utilities,23,73
7,TOUR,Tuniu Corp,Consumer Discretionary,"Hotels, Restaurants & Leisure",23,85
8,NCLH,Norwegian Cruise Line Holdings,Consumer Discretionary,"Hotels, Restaurants & Leisure",167,208
9,M,"Macy's, Inc.",Consumer Discretionary,Multiline Retail,593,775
10,TTEK,Tetra Tech Inc.,Industrials,Commercial Services & Supplies,51,74
11,HTHT,Huazhu Group Limited,Consumer Discretionary,Leisure Equipment & Products,56,97
12,ZOES,"Zoes Kitchen, Inc.",Consumer Discretionary,"Hotels, Restaurants & Leisure",66,165
13,ARLP,Alliance Resource Partners LP,Energy,"Oil, Gas & Consumable Fuels",54,135
14,SPR,Spirit AeroSystems Holdings Inc,Industrials,Aerospace & Defense,68,101
15,SBAC,SBA Communications Corp.,Telecommunication Services,Wireless Telecommunication Services,137,80
16,ENPH,"Enphase Energy, Inc.",Industrials,Electrical Equipment,182,194
17,CPRI,Capri Holdings Limited,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",901,"1,092"
18,TTMI,TTM Technologies Inc.,Information Technology,"Electronic Equip., Instruments",41,81
19,EPAY,Bottomline Technologies Inc.,Information Technology,Software,41,98
20,FCN,"FTI Consulting, Inc.",Industrials,Professional Services,37,55
21,CLMT,Calumet Specialty Products Partners LP,Energy,"Oil, Gas & Consumable Fuels",41,81
22,ATVI,"Activision Blizzard, Inc.",Information Technology,Software,"1,221","1,682"
23,ELLI,"Ellie Mae, Inc.",Information Technology,Software,75,92
24,ORLY,O'Reilly Automotive Inc.,Consumer Discretionary,Specialty Retail,254,292
25,AOSL,Alpha and Omega Semiconductor Limited,Information Technology,Semiconductors,20,38
26,SRE,Sempra Energy,Utilities,Multi-Utilities,58,49
27,WBA,Walgreens Boots Alliance,Consumer Staples,Food & Staples Retailing,531,561
28,UIS,Unisys Corporation,Information Technology,IT Services,48,84
29,KDNY,Chinook Therapeutics,Health Care,Biotechnology,23,33
30,SNA,Snap-on Inc.,Industrials,Machinery,119,168
31,USCR,"U S Concrete, Inc.",Materials,Construction Materials,32,59
32,PFSW,"PFSweb, Inc.",Information Technology,IT Services,12,35
33,NSTG,"NanoString Technologies, Inc.",Health Care,Life Sciences Tools & Services,25,28
34,TRGP,Targa Resources Corp.,Energy,"Oil, Gas & Consumable Fuels",48,79
35,BYND,"Beyond Meat, Inc.",Consumer Staples,Food Products,391,453
36,TTC,Toro Co.,Industrials,Machinery,43,79
37,GGG,Graco Inc.,Industrials,Machinery,47,113
38,XPER,Xperi Corporation,Information Technology,Semiconductors,39,57
39,MTSC,MTS Systems Corp.,Information Technology,"Electronic Equip., Instruments",24,50
40,MCO,Moody's Corp.,Financials,Diversified Financial Services,151,193
41,IDCC,"InterDigital, Inc.",Information Technology,Communications Equipment,39,73
42,XPO,"XPO Logistics, Inc.",Industrials,Air Freight & Logistics,132,157
43,MATX,"Matson, Inc.",Industrials,Marine,21,45
44,MDXG,"MiMedx Group, Inc.",Health Care,Biotechnology,59,73
45,WDFC,WD-40 Company,Consumer Staples,Household & Personal Products,82,266
46,ZBH,"Zimmer Biomet Holdings, Inc.",Health Care,Health Care Equipment & Supplies,101,131
47,MGRC,McGrath Rentcorp,Industrials,Commercial Services & Supplies,19,47
48,MSGS,Madison Square Garden Sports Corp.,Consumer Discretionary,Media,88,140
49,NKTR,Nektar Therapeutics,Health Care,Pharmaceuticals,86,170

In [1084]:
company.to_csv('company_info.csv')

### Final 2b

In [1117]:
tick = ticks

df2 = pd.DataFrame(columns = ['ticker','year','Analysts','values','Analyst_id'])

x=['fq3-2021','fq2-2021','fq1-2021','fq4-2020']
for tic in tick:
    for i in x:
        df=pd.DataFrame()
        options = webdriver.ChromeOptions()
        options.headless = False
        browser = webdriver.Chrome(executable_path = '/Users/arunk/Downloads/chromedriver',chrome_options = options)
        link = 'https://www.estimize.com/'+str.lower(tic)+'/'+i+'?metric_name=eps&chart=historical'
        browser.get(link)
        
        time.sleep(3)

        try:
            browser.find_element_by_xpath('//*[@id="estimates"]/div').click()
        except Exception:
            pass
        df5 = pd.DataFrame()
        df6 = pd.DataFrame()
        t1= browser.find_elements_by_xpath('//*[@id="estimates"]/table/tbody[1]/tr/td/strong')
        t2 =browser.find_elements_by_xpath('//*[@class="estimates-tbl-consensus-column"]/div/strong')

        df5['Analysts'] =  [(i.text) for i in t1]
        df6['Analysts'] =  [(i.text) for i in t2]

        df5 = df5.append(df6,ignore_index=True)

        values = browser.find_elements_by_class_name("estimates-tbl-consensus-eps")
        df5['values'] = [(i.text) for i in values]
        
        df5['ticker'] = [tic for i in values]
        df5['year'] = [i for j in values]
        df5['Analyst_id'] = ['default' for j in values]
        
        Analysts = browser.find_elements_by_xpath('//strong[@class="user-tooltip-item"]')
        df['Analysts'] = [s.text for s in Analysts]
        
        values = browser.find_elements_by_xpath('//td[@class="estimates-tbl-eps"]')
        df['values'] = [s.text for s in values]
        
        Analysts_id = browser.find_elements_by_xpath('//p[@class="user-tooltip-item"]')
        df['Analyst_id'] = [s.text for s in Analysts_id]
        
        df['year'] = [i for s in values]
        df['ticker'] = [tic for s in range(len(values))]



        df2 = df2.append(df,ignore_index=True)
        df2 = df2.append(df5,ignore_index=True)
        


        browser.quit()

In [1118]:
df2.ticker.unique()

array(['CVNA', 'FLEX', 'LZB', 'ARNA', 'ATI', 'DKL', 'UGI', 'TOUR', 'NCLH',
       'M', 'TTEK', 'HTHT', 'ARLP', 'SPR', 'SBAC', 'ENPH', 'CPRI', 'TTMI',
       'EPAY', 'FCN', 'CLMT', 'ATVI', 'ELLI', 'ORLY', 'AOSL', 'SRE',
       'WBA', 'UIS', 'KDNY', 'SNA', 'USCR', 'PFSW', 'NSTG', 'TRGP',
       'BYND', 'TTC', 'GGG', 'XPER', 'MTSC', 'MCO', 'IDCC', 'XPO', 'MATX',
       'WDFC', 'ZBH', 'MGRC', 'MSGS', 'NKTR'], dtype=object)

In [1120]:
df2[df2]

     ticker      year                Analysts values       Analyst_id
0      CVNA  fq3-2021        Brian Nagel, CFA  -0.40   Oppenheimer_26
1      CVNA  fq3-2021           Dominantstock  -0.29    Dominantstock
2      CVNA  fq3-2021         Analyst_9769330  -0.29  Analyst_9769330
3      CVNA  fq3-2021                    Bill  -0.24        BillB1210
4      CVNA  fq3-2021         Analyst_9630672  -0.18  Analyst_9630672
...     ...       ...                     ...    ...              ...
2460   NKTR  fq4-2020          Jay Olson, CFA  -0.80   Oppenheimer_52
2461   NKTR  fq4-2020  NKTR Reported Earnings  -0.65          default
2462   NKTR  fq4-2020      Estimize Consensus  -0.62          default
2463   NKTR  fq4-2020           Estimize Mean  -0.65          default
2464   NKTR  fq4-2020   Wall Street Consensus  -0.68          default

[2465 rows x 5 columns]

In [1119]:
len(df2.Analyst_id.unique())

565

In [1121]:
df2.to_csv('predictions_quarterly.csv')

### Almost Final 2c

In [1146]:
analyst_id1=list(df2.Analyst_id.unique())

In [1156]:

df_analysts=pd.DataFrame()
name=[]
analyst_id=[]
roles=[]
join_date=[]
analyst_confidence=[]
error_rate=[]
accuracy_percentile=[]
points=[]
points_estimate=[]
stocks =[]
pending_estimates = []
count=0
for tic in analyst_id1:
    
    df=pd.DataFrame()

    options = webdriver.ChromeOptions()
    options.headless = False
    browser = webdriver.Chrome(executable_path = '/Users/arunk/Downloads/chromedriver',chrome_options = options)
    link = 'https://www.estimize.com/users/'+str.lower(tic)
    browser.get(link)

    try:

        names = browser.find_element_by_xpath('//h1[@class="profile-display-name"]').text
        name.append(names)

        analyst_log_id = browser.find_element_by_xpath('//p[@class="profile-username"]').text
        analyst_id.append(analyst_log_id)

        roles_an = browser.find_elements_by_xpath('//ul[@class="profile-bio-categorizations"]/li')

        join_date1 = browser.find_element_by_xpath('//div[@class = "profile-activity-stats"]').text.replace('Member since ', '')
        join_date.append(join_date1)

        analyst_confidence1 = browser.find_element_by_xpath('//*[@id="confidence-wrap"]/div/div[2]').text
        analyst_confidence.append(analyst_confidence1)

        error_rate1 = browser.find_element_by_xpath('//div[@class="profile-stat"]').text.replace('%', '')
        error_rate.append(error_rate1)

        accuracy_percentile1 = browser.find_element_by_xpath('//*[@id="profile-tab-wrap"]/div[1]/div[2]/div[1]').text.replace('%', '')
        accuracy_percentile.append(accuracy_percentile1)

        points1 = browser.find_element_by_xpath('//*[@id="profile-tab-wrap"]/div[2]/div[1]/div[1]').text
        points.append(points1)

        points_estimate1 = browser.find_element_by_xpath('//*[@id="profile-tab-wrap"]/div[2]/div[2]/div[1]').text
        points_estimate.append(points_estimate1)

        stocks1 = browser.find_element_by_xpath('//*[@id="profile-tab-wrap"]/div[3]/div[1]/div[1]').text
        stocks.append(stocks1)

        pending_estimates1 = browser.find_element_by_xpath('//*[@id="profile-tab-wrap"]/div[3]/div[2]/div[1]').text
        pending_estimates.append(pending_estimates1)

        if len(roles_an)==0:
            roles.append('None')
        elif len(roles_an)==1:
            roles1 = browser.find_element_by_xpath('//ul[@class="profile-bio-categorizations"]/li[1]')
            rolen = roles1.text
            roles.append(rolen)

        elif len(roles_an)==2:
            roles1 = browser.find_element_by_xpath('//ul[@class="profile-bio-categorizations"]/li[1]')
            roles2 = browser.find_element_by_xpath('//ul[@class="profile-bio-categorizations"]/li[2]')
            rolen = roles1.text+' , '+roles2.text
            roles.append(rolen)

        elif len(roles_an) ==3:

            roles1 = browser.find_element_by_xpath('//ul[@class="profile-bio-categorizations"]/li[1]')
            roles2 = browser.find_element_by_xpath('//ul[@class="profile-bio-categorizations"]/li[2]')
            roles3 = browser.find_element_by_xpath('//ul[@class="profile-bio-categorizations"]/li[3]')
            rolen = roles1.text+', '+roles2.text+' and '+roles3.text
            roles.append(rolen)

        else:
            roles.append('None')

        Analyst_Info = pd.DataFrame(list(zip(name,
                                analyst_id,
                                roles,
                                join_date,
                                analyst_confidence,
                                error_rate,
                                accuracy_percentile,
                                points,
                                points_estimate,
                                stocks ,
                                pending_estimates)),
                               columns =['name','analyst_id','roles','join_date','analyst_confidence','error_rate',
                                'accuracy_percentile','points','points_estimate','stocks','pending_estimates'])
        df_analysts = df_analysts.append(Analyst_Info,ignore_index=True)
    except Exception:
        pass

    browser.quit()

In [1157]:
df_analysts

,name,analyst_id,roles,join_date,analyst_confidence,error_rate,accuracy_percentile,points,points_estimate,stocks,pending_estimates
0,Dominantstock,Dominantstock,"Financial Professional, Buy Side and Asset Man...",Jun 2017 - Last seen 3 months ago,3.2,25.8,21,"-1,041",-7.8,136,215

In [1151]:
new = df_analysts.drop_duplicates().reset_index()

In [1153]:
new = new.drop(columns='index')

In [1158]:
new.to_csv('analysts_info.csv')

In [793]:

Analyst_Info.to_csv('analysts_info.csv')

### 3c Scored and Pending Stocks

In [1159]:
analyst_ids= list(new.analyst_id.unique())
# ['Buck_718700', #'Catooch',
#              'BillB1210',
#              'benjenholdings',
#              'GHS_33',
#              'GHS_46',
#             'Analyst_1035895',
#              'Medic2525'] #['Buck_718700']
#analyst_id

df_stocks_scored = pd.DataFrame(columns=['Ticker','Quarters','Reported','Rank','Eps_Points','Revenue_Points','Total_Points','Analyst_id'])

df_stocks_pend = pd.DataFrame(columns=['Ticker','Quarter','Reports','Published','EPS','Revenue','Analyst_id'])
    
for tic in analyst_ids:
    df_stocks_scored1 = pd.DataFrame(columns=['Ticker','Quarters','Reported','Rank','Eps_Points','Revenue_Points','Total_Points'])
    
    df_stocks_pend1 = pd.DataFrame(columns=['Ticker','Quarter','Reports','Published','EPS','Revenue'])
    
    options = webdriver.ChromeOptions()
    options.headless = False
    browser = webdriver.Chrome(executable_path = '/Users/arunk/Downloads/chromedriver',chrome_options = options)
    link = 'https://www.estimize.com/users/'+str.lower(tic)
    browser.get(link)
    
    import time 
    time.sleep(3)
    #browser.implicitly_wait(5)
    try:
        browser.find_element_by_xpath("//div[@id='profile-pending-estimates']/div[@class='pagination-footer']").click()
    except Exception:
        pass
    try:
        browser.find_element_by_xpath("//div[@id='profile-scored-estimates']/div[@class='pagination-footer']").click()
    except Exception:
        pass
    
    df_stocks_scored1['Ticker']= [i.text for i in  browser.find_elements_by_xpath('//*[@id="profile-scored-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[@class="td"]/strong')]
    df_stocks_scored1['Quarters'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-scored-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[2]')]
    df_stocks_scored1['Reported'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-scored-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[3]')]
    df_stocks_scored1['Rank']= [i.text for i in browser.find_elements_by_xpath("//*[@id='profile-scored-estimates']/div[1]/div[2]/a[@class='linked-row']/div[4]")]
    df_stocks_scored1['Eps_Points']=[i.text for i in browser.find_elements_by_xpath("//*[@id='profile-scored-estimates']/div[1]/div[2]/a[@class='linked-row']/div[5]")]
    df_stocks_scored1['Revenue_Points']=[i.text for i in browser.find_elements_by_xpath("//*[@id='profile-scored-estimates']/div[1]/div[2]/a[@class='linked-row']/div[6]")]
    df_stocks_scored1['Total_Points']=[i.text for i in browser.find_elements_by_xpath("//*[@id='profile-scored-estimates']/div[1]/div[2]/a[@class='linked-row']/div[7]")]
    df_stocks_scored1['Analyst_id']=[tic]*len(browser.find_elements_by_xpath('//*[@id="profile-scored-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[@class="td"]/strong'))

    
    df_stocks_pend1['Ticker'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-pending-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[1]')]
    df_stocks_pend1['Quarter'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-pending-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[2]')]
    df_stocks_pend1['Reports'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-pending-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[3]')]
    df_stocks_pend1['Published'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-pending-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[4]')]
    df_stocks_pend1['EPS'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-pending-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[5]')]
    df_stocks_pend1['Revenue'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-pending-estimates"]/div[1]/div[2]/a[@class="linked-row"]/div[6]')]
    df_stocks_pend1['Analyst_id']=[tic]*len(browser.find_elements_by_xpath("//*[@id='profile-pending-estimates']/div[1]/div[2]/a[@class='linked-row']/div[1]"))
    
    df_stocks_scored = df_stocks_scored.append(df_stocks_scored1,ignore_index=True)
    
    df_stocks_pend=df_stocks_pend.append(df_stocks_pend1,ignore_index=True)
    
    browser.quit()

In [1162]:
df_stocks_scored.to_csv('stocks_scored.csv')

In [1163]:
df_stocks_pend.to_csv('stocks_pending.csv')

### 2C ix Analysts Stocks Covered

In [1178]:
analyst_ids=list(new.analyst_id.unique())
# ['Buck_718700','BillB1210']
df_stocks_cov = pd.DataFrame(columns=['Ticker','Reports','Quarters','Points','Pts_Est','Error_Rate','Accuracy','Analyst_id'])
    
for tic in analyst_ids:
    df_stocks_cov1 = pd.DataFrame()
    options = webdriver.ChromeOptions()
    options.headless = False
    browser = webdriver.Chrome(executable_path = '/Users/arunk/Downloads/chromedriver',chrome_options = options)
    link = 'https://www.estimize.com/users/'+str.lower(tic)
    browser.get(link)
    browser.refresh()
    
    import time
    time.sleep(10)
    
    #browser.implicitly_wait(3)
    try:
        browser.find_element_by_xpath('//*[@id="profile-covered-stocks"]/div[2]').click()
    except Exception:
        pass

    df_stocks_cov1['Ticker']= [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[1]')]
    
    df_stocks_cov1['Reports'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[2]')]
    df_stocks_cov1['Quarters'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[3]')]
    df_stocks_cov1['Points'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[4]')]
    df_stocks_cov1['Error_Rate'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[6]')]
    df_stocks_cov1['Accuracy'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[7]')]
    df_stocks_cov1['Analyst_id'] = [tic]*len(browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[1]'))
    df_stocks_cov1['Pts_Est'] = [i.text for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[5]')]

    df_stocks_cov = df_stocks_cov.append(df_stocks_cov1,ignore_index=True)
    print(df_stocks_cov.shape)
    browser.quit()

In [1179]:
# for i in browser.find_elements_by_xpath('//*[@id="profile-covered-stocks"]/div[1]/div[2]/div/div[4]'):
#     print(i.text)
df_stocks_cov.shape

(60, 8)

In [1180]:
df_stocks_cov

   Ticker Reports Quarters Points Pts_Est Error_Rate Accuracy     Analyst_id
0    AAPL   Feb 1       16   -125    -7.8      11.8%      20%  Dominantstock
1     JBT  Feb 22       16     73     4.6      10.1%      27%  Dominantstock
2    VEEV   Mar 1       15    -61    -4.1       8.7%      16%  Dominantstock
3     CAT  Jan 27       15   -254   -16.9      19.6%      13%  Dominantstock
4    BABA   Feb 2       15     23     1.5      11.7%      40%  Dominantstock
5    ALGN   Feb 3       15   -103    -6.9      26.0%      17%  Dominantstock
6      WB   Mar 2       15   -321   -20.7      17.5%       9%  Dominantstock
7    MOMO  Mar 15       15   -266   -17.7      28.0%       9%  Dominantstock
8    PANW   Mar 1       15    -70    -4.7       9.4%      18%  Dominantstock
9     RJF  Jan 26       14   -196   -13.5      14.4%      14%  Dominantstock
10   LRCX  Jan 26       14   -327   -23.4      14.6%       7%  Dominantstock
11   ANET  Feb 17       14   -153   -10.9       8.0%      13%  Dominantstock
12   AEIS  Jan 31       14   -180   -12.4      28.8%      21%  Dominantstock
13   LOPE  Feb 16       13     22     1.7       5.6%      29%  Dominantstock
14     EA   Feb 1       13   -125    -9.6      18.9%      17%  Dominantstock
15   MKSI   Feb 1       13   -247     -19      17.6%       8%  Dominantstock
16   YELP   Feb 9       13   -175     -13      43.2%       8%  Dominantstock
17   COHR   Feb 9       13   -218   -16.8      28.2%      15%  Dominantstock
18   AMAT  Feb 16       13   -158   -12.2      10.2%      12%  Dominantstock
19     SQ   Mar 2       12     63       5      24.7%      33%  Dominantstock
20   FANG  Feb 15       12   -204     -17      29.9%      11%  Dominantstock
21   ABMD   Feb 3       12   -172   -14.3      19.5%      19%  Dominantstock
22    BAC  Jan 18       12   -115    -9.6      19.9%      13%  Dominantstock
23      C  Jan 14       12    -49    -4.1      18.5%      23%  Dominantstock
24     FB   Feb 2       12     51     4.3       9.5%      41%  Dominantstock
25     DQ   Mar 8       11    -97    -8.9      33.7%      24%  Dominantstock
26   OLLI   Apr 6       11     21     1.9      12.6%      31%  Dominantstock
27   GRUB  Dec 10       11    -88      -8      44.4%      21%  Dominantstock
28   MTOR   Feb 2       11     40     3.6      12.8%      36%  Dominantstock
29   LGIH   Mar 1       10   -237   -23.7      21.1%       6%  Dominantstock
30      F  Jan 27        2     11     5.5      40.7%      47%      Neverever
31   CRWD  Mar 24        2     48      24      11.1%      62%      Neverever
32     PG  Jan 25        1     10      10       2.8%      51%      Neverever
33    UAA  Feb 15        1    -11     -11      36.5%      14%      Neverever
34    DIS   Feb 8        1     -3      -3      26.5%      79%      Neverever
35   SBUX  Jan 27        1     -7      -7       5.5%      52%      Neverever
36   ULTA  Mar 10        1    -11     -11      21.9%      19%      Neverever
37    PFE   Feb 1        1     -6      -6      14.9%      38%      Neverever
38     BA  Jan 26        1     16      16      51.1%      60%      Neverever
39     GE  Jan 27        1      9       9      12.1%      64%      Neverever
40    UPS   Feb 1        1     -8      -8       5.3%      44%      Neverever
41   AAPL   Feb 1        1     -3      -3       3.2%      77%      Neverever
42   QCOM   Feb 2        1     21      21       6.9%      59%      Neverever
43   ETSY   Mar 1        1     -9      -9      11.4%      44%      Neverever
44    AMD   Feb 1        1     23      23       5.7%      57%      Neverever
45   INTC  Jan 26        1     15      15      18.5%      47%      Neverever
46   NVDA  Feb 17        1     31      31       2.3%      68%      Neverever
47   NXPI   Feb 2        1     36      36       1.7%      67%      Neverever
48    TXN  Jan 26        1     -2      -2       1.1%      74%      Neverever
49      V   Feb 3        1     41      41       0.6%      82%      Neverever
50   ATVI  Feb 10        1     -5      -5       5.0%      66%      Neverever
51    CRM   Mar 1        1     28      28      11.9%      53%      Neverever
52   PYPL   Feb 2        1     17      17       1.2%      76%      Neverever
53     SQ   Mar 2        1     -6      -6      27.6%      56%      Neverever
54   SNAP   Feb 8        1    -21     -21      43.1%       1%      Neverever
55   DOCU  Mar 17        1     26      26       6.8%      63%      Neverever
56   LYFT  Feb 15        1     -6      -6      50.5%      53%      Neverever
57   UBER   Feb 9        1      5       5      43.4%      58%      Neverever
58   BYND   Mar 3        1     33      33      26.9%      85%      Neverever
59   PTON   Feb 9        1     44      44       3.8%      74%      Neverever

In [341]:
!pip3 install ipython-sql
!pip3 install mysqlclient
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

In [345]:
import pymysql

import pandas as pd

conn=pymysql.connect(host='localhost',port=int(3306),user='root',passwd='NatiAug!#10',db='largeco')

dfer=pd.read_sql_query("SELECT * FROM lgline ",conn)

# print(df)

In [346]:
dfer

       INV_NUM  LINE_NUM  PROD_SKU  LINE_QTY  LINE_PRICE
0        104.0       1.0  6041-PBS       2.0        7.49
1        104.0       2.0  8523-UCB       1.0       21.59
2        104.0       3.0  6451-KGJ       1.0        6.99
3        105.0       1.0  8841-JFP       1.0        6.59
4        106.0       1.0  9324-PPG       2.0       11.99
...        ...       ...       ...       ...         ...
11758   3454.0       1.0  3061-DOI       5.0        5.59
11759   3454.0       2.0  4132-QIN       3.0        9.29
11760   3454.0       3.0  5437-WBO       4.0       28.99
11761   3454.0       4.0  5413-TTF       2.0       26.99
11762   3454.0       5.0  1099-WFZ       5.0       14.99

[11763 rows x 5 columns]

In [748]:
import mysql.connector as msql
from mysql.connector import Error
try:
    conn = msql.connect(host='localhost', user='root',  
                        password='NatiAug!#10')#give ur username, password
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("CREATE DATABASE Estimize")
        print("Database is created")
except Error as e:
    print("Error while connecting to MySQL", e)

Database is created

In [752]:
import mysql.connector as msql
from mysql.connector import Error
try:
    conn = msql.connect(host='localhost', database='estimize', user='root', password='NatiAug!#10')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS company_info;')
        print('Creating table....')
# in the below line please pass the create table statement which you want #to create
        cursor.execute("CREATE TABLE company_info(tickers varchar(255),names varchar(255),sectors varchar(255),industries varchar(255),number_of_followers varchar(255),number_of_analysts varchar(255))")
        print("Table is created....")
        #loop through the data frame
        for i,row in company.iterrows():
            #here %S means string values 
            sql = "INSERT INTO estimize.company_info VALUES (%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not auto committed by default, so we must commit to save our changes
            conn.commit()
except Error as e:
            print("Error while connecting to MySQL", e)

You're connected to database:  ('estimize',)
Creating table....
Table is created....
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [ ]:
import mysql.connector as msql
from mysql.connector import Error
try:
    conn = msql.connect(host='localhost', database='estimize', user='root', password='NatiAug!#10')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS predictions_quarterly;')
        print('Creating table....')
# in the below line please pass the create table statement which you want #to create
        cursor.execute("CREATE TABLE predictions_quarterly(ticker varchar(255),year varchar(255),Analysts varchar(255),values float,analyst_id varchar(255))")
        print("Table is created....")
        #loop through the data frame
        for i,row in company.iterrows():
            #here %S means string values 
            sql = "INSERT INTO estimize.predictions_quarterly VALUES (%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql, tuple(row))
            #print("Record inserted")
            # the connection is not auto committed by default, so we must commit to save our changes
            conn.commit()
except Error as e:
            print("Error while connecting to MySQL", e)

In [ ]:
import mysql.connector as msql
from mysql.connector import Error
try:
    conn = msql.connect(host='localhost', database='estimize', user='root', password='NatiAug!#10')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS predictions_quarterly;')
        print('Creating table....')
# in the below line please pass the create table statement which you want #to create
        cursor.execute("CREATE TABLE predictions_quarterly(ticker varchar(255),year varchar(255),Analysts varchar(255),values float,analyst_id varchar(255))")
        print("Table is created....")
        #loop through the data frame
        for i,row in company.iterrows():
            #here %S means string values 
            sql = "INSERT INTO estimize.predictions_quarterly VALUES (%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql, tuple(row))
            #print("Record inserted")
            # the connection is not auto committed by default, so we must commit to save our changes
            conn.commit()
except Error as e:
            print("Error while connecting to MySQL", e)

In [ ]:
import mysql.connector as msql
from mysql.connector import Error
try:
    conn = msql.connect(host='localhost', database='estimize', user='root', password='NatiAug!#10')
    if conn.is_connected():
        cursor = conn.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor.execute('DROP TABLE IF EXISTS predictions_quarterly;')
        print('Creating table....')
# in the below line please pass the create table statement which you want #to create
        cursor.execute("CREATE TABLE predictions_quarterly(name varchar(255),analyst_id varchar(255),roles varchar(255),join_date varchar(255),analyst_confidence int,	error_rate int,	accuracy_percentile int, points int ,	points_estimate int, stocks int, pending_estimates int)")
        print("Table is created....")
        #loop through the data frame
        for i,row in predictions_quarterly.iterrows():
            #here %S means string values 
            sql = "INSERT INTO estimize.predictions_quarterly VALUES (%s,%s,%s,%s,%s,%s)"
            cursor.execute(sql, tuple(row))
            #print("Record inserted")
            # the connection is not auto committed by default, so we must commit to save our changes
            conn.commit()
except Error as e:
            print("Error while connecting to MySQL", e)